@startuml
'https://plantuml.com/class-diagram

class Cookie{

'The value of the cookie itself.
-String name;
-String value;
'Attributes encoded in the header's cookie fields.
-String comment;
-String domain;
-int maxAge = -1;
-String path;
-boolean secure;
-int version = 0;
-boolean isHttpOnly = false;
}



@enduml