@startuml
'https://plantuml.com/class-diagram

interface Session{

+long getCreationTime();
+String getId();
+long getLastAccessedTime();
+ServletContext getServletContext();
+void setMaxInactiveInterval(int interval);
+int getMaxInactiveInterval();
+Object getAttribute(String name);
+Enumeration<String> getAttributeNames();
+void setAttribute(String name, Object value);
+void removeAttribute(String name);
+void invalidate();
+boolean isNew();
}

@enduml