@startuml
'https://plantuml.com/class-diagram


interface ApplicationContext

interface EnvironmentCapable
interface ListableBeanFactory
interface HierarchicalBeanFactory
interface MessageSource
interface ApplicationEventPublisher
interface ResourcePatternResolver

EnvironmentCapable <|-- ApplicationContext
MessageSource <|-- ApplicationContext
ApplicationEventPublisher <|-- ApplicationContext
ResourcePatternResolver <|-- ApplicationContext

ListableBeanFactory <|-- ApplicationContext
HierarchicalBeanFactory <|-- ApplicationContext
@enduml
