@startuml
'https://plantuml.com/class-diagram

abstract class AbstractOwnableSynchronizer{
- transient Thread exclusiveOwnerThread

# final void setExclusiveOwnerThread(thread)

# final Thread getExclusiveOwnerThread()
}

abstract class AbstractQueuedSynchronizer{
-volatile int state
- transient volatile Node head
- transient volatile Node tail
}



AbstractOwnableSynchronizer<|--AbstractQueuedSynchronizer

@enduml